
services:
  db:
    image: postgres:15-alpine
    container_name: hotel-hub-db
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel-hub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel_user -d hotel_db"]
      interval: 30s
      timeout: 10s
      retries: 1
    restart: unless-stopped

  app:
    build: .
    container_name: hotel-hub-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/hotel_db
      QUARKUS_DATASOURCE_USERNAME: hotel_user
      QUARKUS_DATASOURCE_PASSWORD: hotel_pass
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hotel-hub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  hotel-hub-network:
    driver: bridge
